name: Build Binaries

on:
  push:
    branches:
      - dev
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    branches:
      - dev
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  build:
    name: Build Binary
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            binary_name: usque.exe
            asset_name: usque-windows-amd64.exe
          - os: ubuntu-latest
            binary_name: usque
            asset_name: usque-linux-amd64
          - os: macos-latest
            binary_name: usque
            asset_name: usque-darwin-amd64

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Build Binary
        run: |
          go build -v -o ${{ matrix.binary_name }}

      - name: Generate Release Tag
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        id: tag
        run: |
          echo "tag=v$(cat VERSION)" >> $env:GITHUB_OUTPUT

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        uses: softprops/action-gh-release@v1
        with:
          name: Dev Build ${{ steps.tag.outputs.tag }}
          tag_name: ${{ steps.tag.outputs.tag }}
          files: ${{ matrix.binary_name }}
          prerelease: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
